# Generated by Django 5.2 on 2025-05-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_tarea_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='gris', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='tareas.etiqueta'),
        ),
    ]
