# Generated by Django 5.2 on 2025-05-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_etiqueta_tarea_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
