# Generated by Django 5.2 on 2025-05-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tareas.tarea'),
        ),
    ]
