# Generated by Django 5.2 on 2025-05-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_usuario_fecha_nacimiento_usuario_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
